SET IDENTITY_INSERT [dbo].[loandetail] ON
INSERT INTO [dbo].[loandetail] ([id], [name], [package], [minAmount], [maxAmount], [count], [date], [rate], [terms], [website], [duration]) VALUES (1, N'Page Financials', N'Personal', 200000, 5000000, 1, N'1900-01-01', 12, N'Our rates and repayment terms are straightforward and clear so you know exactly what you have to payback for the duration of the loan no matter how much you borrow.', N'https://pagefinancials.com/', 12)
INSERT INTO [dbo].[loandetail] ([id], [name], [package], [minAmount], [maxAmount], [count], [date], [rate], [terms], [website], [duration]) VALUES (2, N'Migo Money', N'Individual', 500, 500000, 2, N'1900-01-01', 5, N'We aim to make you an offer every time you make a request, no matter how small. However, in instances where we are unable to ascertain your personal information, we may not be able to make you an offer.', N'https://www.migo.money/get-a-loan/', 15)
INSERT INTO [dbo].[loandetail] ([id], [name], [package], [minAmount], [maxAmount], [count], [date], [rate], [terms], [website], [duration]) VALUES (3, N'LendUp', N'LendUp Basic', 10000, 100000, 0, N'1900-01-01', 20, N'LendUp is a socially responsible direct lender dedicated to helping our customers meet their short term needs.', N'https://www.lendup.com/apply', 6)
INSERT INTO [dbo].[loandetail] ([id], [name], [package], [minAmount], [maxAmount], [count], [date], [rate], [terms], [website], [duration]) VALUES (6, N'C24 Limited', N'Business', 50000, 3000000, 0, N'1900-01-01', 11, N'CALL US AT
090 90896919
contact@c24.com.ng', N'https://c24ng.com/loan_application/continueapplication2.php', 18)
INSERT INTO [dbo].[loandetail] ([id], [name], [package], [minAmount], [maxAmount], [count], [date], [rate], [terms], [website], [duration]) VALUES (8, N'Specta', N'Specta Prime', 5000, 5000000, 0, N'1900-01-01', 25, N'Get up to 2 Million in 5 minutes, no profiling, open to everyone!', N'https://www.myspecta.com/Home/Basic', 10)
INSERT INTO [dbo].[loandetail] ([id], [name], [package], [minAmount], [maxAmount], [count], [date], [rate], [terms], [website], [duration]) VALUES (11, N'C24 Limited', N'Personal', 5000, 200000, 0, N'1900-01-01', 10, N'The fastest cash backed lending! Get a loan while you earn interest on your investment.', N'https://c24ng.com/loan_application/continueapplication2.php', 14)
INSERT INTO [dbo].[loandetail] ([id], [name], [package], [minAmount], [maxAmount], [count], [date], [rate], [terms], [website], [duration]) VALUES (12, N'C24 Limited', N'Lux', 200000, 800000, 0, N'1900-01-01', 9, N'Reach Us on WhatsApp 
081 0315 5826
Call Us On: 
090 9089 7471', N'https://c24ng.com/loan_application/continueapplication2.php', 12)
INSERT INTO [dbo].[loandetail] ([id], [name], [package], [minAmount], [maxAmount], [count], [date], [rate], [terms], [website], [duration]) VALUES (14, N'Specta', N'Specta Premuim', 20000, 2000000, 0, N'1900-01-01', 7, N'Fast & Easy Application Process.', N'https://www.myspecta.com/Home/Basic', 12)
INSERT INTO [dbo].[loandetail] ([id], [name], [package], [minAmount], [maxAmount], [count], [date], [rate], [terms], [website], [duration]) VALUES (16, N'Specta', N'Specta Power', 50000, 5000000, 0, N'1900-01-01', 13, N'Giving you 100% of your salary on a card to use anytime, any day.', N'https://www.myspecta.com/Home/Basic', 10)
SET IDENTITY_INSERT [dbo].[loandetail] OFF
